[package]
name = "remote-pty-slave"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["staticlib"]

[dependencies]
remote-pty-common = { path = "../remote-pty-common" }
libc = "0.2.90"
lazy_static = "1.4.0"
bincode = "2.0.0-rc.1"
errno = "0.2.7"
